print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("mfdsfafasdfsafas")
print("mfdsfafasdfsafas")
print("mfdsfafasdfsafas")
print("knfsdakljskdjskaljkl")
print("knfsdakljskdjskaljkl")
print("knfsdakljskdjskaljkl")
print("pputanginaa mo")