print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("m")
print("mfdsfafasdfsafas")
print("mfdsfafasdfsafas")
print("mfdsfafasdfsafas")
print("knfsdakljskdjskaljkl")
print("knfsdakljskdjskaljkl")
print("knfsdakljskdjskaljkl")
print("hello abuiza")
print("hello abuiza")
print("hello abuiza")
print("pangit mo")
print("pangit mo")
print("pangit mo")
print("pangit mo")